STORAGE:
  SOURCE_DIRECTORY: "SOURCE_DOCUMENTS"
  DB: "DB"
  CACHE_DB_PATH: "DB/langchain_cache.db"
  MODELS: "models"

  INGEST_LOG: "logs/file_ingest.log"
  HISTORY_DIR: "local_chat_history"
  HISTORY_FILE: "qa_log.csv"
